### ISSUE TITLE
install

### ISSUE THREAD

**Issue by dicook** [srkob1/taipan#2]
Using devtools, install() fails at the very end:

* installing *source* package ‘taipan’ ...
** R
** tests
** byte-compile and prepare package for lazy loading
Error in list_files_with_exts(file.path("../images"), c("jpg", "jpeg",  : 
  could not find function "list_files_with_exts"
Error : unable to load R code in package ‘taipan’
ERROR: lazy loading failed for package ‘taipan’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/taipan’
Error: Command failed (1)

it looks like a library isn't loaded, so that "list_files_with_exts" can't be found

**Comment by mitchelloharawild** [comment]
Resolved in 485a4867f5ab6b08ba0210cafb9a420a0aaa7a08
